### ISSUE TITLE
version 1.0.4 not working

### ISSUE THREAD

**Issue by apollocreed** [MicroFocus/octane-gocd-plugin#21]
Hello !
I've a go-server in Version: 19.12.0 (10888-29b0f854605987c8edab9dced4814b62dc751a11).
installed on centos via RPM.
I've downloaded and put the jar file in the right directory permission 755 user go.
however the plugin fail to be launched correctly i.e. image 
Please tell me what is wrong 

Many thanks
![image](https://user-images.githubusercontent.com/2979682/73062883-b83cc780-3e9d-11ea-8525-bdd0803e4201.png)

**Comment by lazara3** [comment]
**Hello apollocreed**

I’m glad to see that you are trying to use the plugin.

**Few question:**

1. Did you try to install the plugin with 777 permission?
2. Can you please try to install the plugin again and check the logs, see if you have any information about the plugin?
Relevant logs: 

- GoServer\logs\go-server.log
- GoServer\logs\plugin-microfocus.adm.octane.ciplugins.gocd.log
- GoServer\nga\logs\nga.log

3. Can you please check that the plugin on your machine is not corrupted? 
Extract the jar file and see if you can see the plugin.xml under the main direactory.

**Thanks
Ayellet.**

**Comment by apollocreed** [comment]
Hey @lazara3 
thanks that solved it i.e. chmod 777

**Comment by lazara3** [comment]
Great to hear!
We'd love to hear more feedbacks on using our plugin
